language: python
python:
  - "2.6"
  - "2.7"
before_install: sudo apt-get install -qq libblas-dev gfortran liblapack-dev
# command to install dependencies. ordereddict is only needed for Python 2.6, hence not in requirements.txt
install:
  - "pip install -q ordereddict"
  - "travis_wait pip install -q -r requirements.txt"
# command to run tests
script:
  - nosetests
  - make -C doc html
